# Generated by Django 5.1.7 on 2025-04-20 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0004_alter_skinprediction_prediction'),
    ]

    operations = [
        migrations.AddField(
            model_name='skinprediction',
            name='confidence',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
